---
- name: AddJavaEnv
  lineinfile: dest=/etc/profile line={{item}}
  with_items:
    - "###### Add Java Env begin ######"
    - "export JAVA_HOME=/usr/local/jdk1.8.0_151"
    - "export JRE_HOME=${JAVA_HOME}/jre"
    - "export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib"
    - "export PATH=${JAVA_HOME}/bin:$PATH"
    - "###### Add Java Env End ######"
