---
- script: supervisor_install.sh
  register: supervisor_install_out
  ignore_errors: True
  tags: supervisor_install
  
- debug: msg={{supervisor_install_out.stdout_lines}}
  tags: supervisor_install_out
